class Constants {
  Constants._();

  static final List<String> LOCATIONS = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Raleigh",
    "Miami",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Tampa",
    "Arlington",
    "New Orleans",
    "Wichita",
    "Cleveland",
    "Bakersfield",
    "Aurora",
    "Anaheim",
    "Honolulu",
    "Santa Ana",
    "Riverside",
    "Corpus Christi",
    "Lexington",
    "Henderson",
    "Stockton",
    "St. Paul",
    "Cincinnati",
    "St. Louis",
    "Pittsburgh",
    "Greensboro",
    "Lincoln",
    "Anchorage",
    "Plano",
    "Orlando",
    "Irvine",
    "Newark",
    "Durham",
    "Chula Vista",
    "Toledo",
    "Fort Wayne",
  ];

  static final List<String> MASCOTS = [
    "Tigers",
    "Eagles",
    "Bulldogs",
    "Lions",
    "Panthers",
    "Wolves",
    "Bears",
    "Hawks",
    "Sharks",
    "Dragons",
    "Knights",
    "Warriors",
    "Wildcats",
    "Cougars",
    "Mustangs",
    "Falcons",
    "Trojans",
    "Rams",
    "Spartans",
    "Pirates",
    "Vikings",
    "Raiders",
    "Huskies",
    "Bobcats",
    "Jaguars",
    "Bison",
    "Foxes",
    "Gators",
    "Hurricanes",
    "Leopards",
    "Otters",
    "Pandas",
    "Penguins",
    "Phoenix",
    "Ravens",
    "Rhinos",
    "Scorpions",
    "Sea Lions",
    "Stallions",
    "Thunderbirds",
    "Titans",
    "Vultures",
    "Wolverines",
    "Coyotes",
    "Grizzlies",
    "Mavericks",
    "Owls",
    "Peacocks",
    "Pelicans",
    "Rattlers",
    "Roadrunners",
    "Sabres",
    "Salamanders",
    "Seahawks",
    "Sphinxes",
    "Tarantulas",
    "Terriers",
    "Tortoises",
    "Unicorns",
    "Vipers",
    "Walruses",
    "Wizards",
    "Yellow Jackets",
    "Zebras",
    "Antelopes",
    "Barracudas",
    "Centaurs",
    "Chameleons",
    "Cobras",
    "Dolphins",
    "Fireflies",
    "Geckos",
    "Gladiators",
    "Griffins",
  ];

  static final List<String> FIRST_NAMES = [
  "James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Charles",
  "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
  "Kenneth", "Kevin", "Brian", "George", "Edward", "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan",
  "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon",
  "Benjamin", "Samuel", "Gregory", "Frank", "Alexander", "Raymond", "Patrick", "Jack", "Dennis", "Jerry",
  "Tyler", "Aaron", "Jose", "Henry", "Douglas", "Adam", "Peter", "Nathan", "Zachary", "Walter",
  "Kyle", "Harold", "Carl", "Jeremy", "Gerald", "Keith", "Roger", "Arthur", "Terry", "Lawrence",
  "Sean", "Christian", "Albert", "Joe", "Ethan", "Austin", "Jesse", "Willie", "Billy", "Bryan",
  "Bruce", "Jordan", "Ralph", "Roy", "Noah", "Dylan", "Eugene", "Wayne", "Alan", "Juan",
  "Louis", "Russell", "Gabriel", "Randy", "Philip", "Harry", "Vincent", "Bobby", "Johnny", "Logan"
];

static final List<String> LAST_NAMES = [
  "Smith", "Johnson", "Williams", "Jones", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor",
  "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
  "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King",
  "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter",
  "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins",
  "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey",
  "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez",
  "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross",
  "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington",
  "Butler", "Simmons", "Foster", "Gonzales", "Bryant", "Alexander", "Russell", "Griffin", "Diaz", "Hayes"
];

static final List<String> CONFERENCE_NAMES = ["KWZ", "PPL", "MCN", "RES", "QJD"];

}